spring.application.name=hospital
server.port=8090
#database connection jdbc for any connect may it be sql postgress mongo db
spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Optional: Show SQL queries
spring.jpa.show-sql=true
# Optional: Automatically create/update tables
spring.jpa.hibernate.ddl-auto=create
#none validate create
# Optional: Hibernate dialect
# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# SQL Initialization
# ===============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=classpath.data.sql
spring.jpa.defer-datasource-initialization=true

#To store constant values in application.properties and read them 
#dynamically in Spring Boot, use the @Value annotation.
#This allows you to update pricing or discount rates without recompiling your Java code.
#thus defining in application properties
#Step 1: Add keys to application.properties
# Hospital Billing Configuration
#hospital.billing.insurance-coverage-rate=0.80
#hospital.billing.self-pay-discount-rate=0.10
#hospital.billing.standard-consultation-fee=100.00
#OR Inject values into your Service class
#Use @Value("${property.key:default_value}") directly on private fields
#see more on insurancebillingcalculationservice